### PR TITLE
Minor change in demo11

### PR DESCRIPTION
**Pull request by feng-li**
I think the `gg_animate()` function changes to `gganimate()` in the newest `gganimate` package.

### CODE REVIEW

**Comment by avehtari** [comment]
Hi @feng-li, 
Is it going to change at once, or are there going to be versions where both work?

Aki

**Comment by feng-li** [comment]
I don't know actually. I can only find `gganimate()` in  the newest `gganimate` package.

**Comment by avehtari** [comment]
Hi @feng-li 
We haven't merged this pull request because version problems with gganimate.
Now you added without any explanation many commits which are not related to gganimate.
Was this accident or would you like to make separate issues and/or pull requests for your new proposed changes?

**Comment by feng-li** [comment]
I just pulled your version and merged it to my forked repo. I did not change anything on your repo (I did not have any permissions to do so.) It is weird. Anything I can do from my side?

**Comment by avehtari** [comment]
Correct, you didn't change anything in my repo, but you updated your pull request. Initially your pull request has only the gganimate change. Now the pull request includes lot of your local changes. One option is to close this pull request, add an issue about gganimate (to wait that the new gganimate version becomes the default), add issues for other problems you found and if you have good proposal for improving then make separate focused pull requests.

**Comment by feng-li** [comment]
OK. Let me close this. I even forgot here is an open pull request. I did not know any of my updates in my forked repo will update here. Sorry for the inconvenience.

**Pull request closed without merging**
